server:
  port: 9003
spring:
  application:
    name: API-GATEWAY
  cloud:
    gateway:
      routes:
      - id: USER-SERVICE
        uri: lb://USER-SERVICE
        predicates:
        - Path=/users/**
      - id: ADDRESS-SERVICE
        uri: lb://ADDRESS-SERVICE
        predicates:
        - Path=/address/**
  main:
    web-application-type: reactive
  liquibase:
    change-log:

management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream

hystrix:
  command:
    fallbackCmd:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 5000

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      default-zone: http://localhost:8761/eureka/
  instance:
    hostname: localhost
