server:
  port: 9002
spring:
  application:
    name: ADDRESS-SERVICE
  datasource:
    url: jdbc:mysql://localhost:3306/spring_microservice_address
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    generate-ddl: true
    hibernate:
      ddl-auto: none
  cloud:
    config:
      enabled: true
      uri: http://localhost:9006
  liquibase:
    change-log: classpath:dblogs/changelog/changelog-master.xml
